### --- Create Task ---
POST http://{{host}}/tasks
Content-Type: application/json

{
  "title": "Sample Task",
  "description": "This is a sample task.",
  "dueDate": "2024-02-15"
}

### --- Get All Tasks ---
GET http://{{host}}/tasks

### --- Get Task by ID ---
GET http://{{host}}/tasks/1

### --- Update Task ---
PUT http://{{host}}/tasks/1
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "This is an updated task description.",
  "dueDate": "2024-02-20"
}

### --- Delete Task ---
DELETE http://{{host}}/tasks/1

###




